apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-nfs
  storageClassName: ''
