apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-hp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-hp
  storageClassName: ''
