apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-configmap
data:
  MYSQL_DATABASE: "cake"
  MYSQL_USER: "cccr"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-configmap
data:
  DB_HOST: "{{ .Release.Name }}-db-svc" 
  DB_USER: "cccr"
  DB_NAME: "cake"
  FLASK_APP: "run.py"
