apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        envFrom: 
        - secretRef:
            name: {{ .Release.Name }}-db-secret
        - configMapRef:
            name: {{ .Release.Name }}-db-configmap
        volumeMounts:
        - name: {{ .Release.Name }}-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Release.Name }}-db-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-hp # hostPath 사용 설정
          #claimName: {{ .Release.Name }}-pvc-nfs # nfs 사용 설정
