apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job-flask
spec:
  template:
    metadata:
      labels:
        app: job-db-upgrade
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-upgrade
        image: freedom98/flask:k3.0
        command: ["flask", "db", "upgrade"]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-web-configmap
        - secretRef:
            name: {{ .Release.Name }}-web-secret
