apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-hp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/hostPath-volume
    type: DirectoryOrCreate
