apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "P@ssw0rd"
  MYSQL_PASSWORD: "P@ssw0rd"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secret
type: Opaque
stringData:
  DB_PASSWORD: "P%40ssw0rd"
